
tasks:
  - init: npm install && npm run build
    command: npm run start

ports:
  - port: 3000
    onOpen: open-preview

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - dbaeumer.vscode-eslint