-- MySQL Script generated by MySQL Workbench
-- dom 24 ott 2021, 23:35:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlmanaccoCivile` DEFAULT CHARACTER SET utf8 ;
USE `AlmanaccoCivile` ;

-- -----------------------------------------------------
-- Table `AlmanaccoCivile`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmanaccoCivile`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `has_admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmanaccoCivile`.`utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmanaccoCivile`.`utente` (
  `nickname` VARCHAR(25) NOT NULL,
  `nome` VARCHAR(25) NOT NULL,
  `cognome` VARCHAR(25) NOT NULL,
  `password` VARCHAR(71) NOT NULL,
  `fk_idadmin` INT NOT NULL,
  PRIMARY KEY (`nickname`),
  INDEX `fk_utente_admin_idx` (`fk_idadmin` ASC),
  CONSTRAINT `fk_utente_admin`
    FOREIGN KEY (`fk_idadmin`)
    REFERENCES `AlmanaccoCivile`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmanaccoCivile`.`data_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmanaccoCivile`.`data_evento` (
  `iddata_evento` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  PRIMARY KEY (`iddata_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmanaccoCivile`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmanaccoCivile`.`evento` (
  `idevento` INT NOT NULL AUTO_INCREMENT,
  `titolo` VARCHAR(200) NOT NULL,
  `descrizione` LONGTEXT NOT NULL,
  `path_immagine` VARCHAR(500) NOT NULL,
  `link_articolo` VARCHAR(500) NOT NULL,
  `visualizzazioni` INT NOT NULL,
  `rilevanza` FLOAT NOT NULL,
  `fk_iddata_evento` INT NOT NULL,
  PRIMARY KEY (`idevento`),
  INDEX `fk_evento_data_evento1_idx` (`fk_iddata_evento` ASC),
  CONSTRAINT `fk_evento_data_evento1`
    FOREIGN KEY (`fk_iddata_evento`)
    REFERENCES `AlmanaccoCivile`.`data_evento` (`iddata_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmanaccoCivile`.`utente_has_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmanaccoCivile`.`utente_has_evento` (
  `fk_nickname` VARCHAR(25) NOT NULL,
  `fk_idevento` INT NOT NULL,
  PRIMARY KEY (`fk_nickname`, `fk_idevento`),
  INDEX `fk_utente_has_evento_evento1_idx` (`fk_idevento` ASC),
  INDEX `fk_utente_has_evento_utente1_idx` (`fk_nickname` ASC),
  CONSTRAINT `fk_utente_has_evento_utente1`
    FOREIGN KEY (`fk_nickname`)
    REFERENCES `AlmanaccoCivile`.`utente` (`nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utente_has_evento_evento1`
    FOREIGN KEY (`fk_idevento`)
    REFERENCES `AlmanaccoCivile`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;